<a href="https://colab.research.google.com/github/armandoordonez/deeplearning/blob/main/Broadcasting_example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

A = np.array([[10.0,0.0,4.5,68.0],[30.0,5.0,4.5,68.0],[40.0,4.0,0.5,68.0],[20.0,1.0,0.5,67.0]])
print (A)

[[10.   0.   4.5 68. ]
 [30.   5.   4.5 68. ]
 [40.   4.   0.5 68. ]
 [20.   1.   0.5 67. ]]


In [ ]:
suma = np.sum(A, axis=0)
print(suma)

[100.  10.  10. 271.]


In [ ]:
print(A/suma)

[[0.1        0.         0.45       0.25092251]
 [0.3        0.5        0.45       0.25092251]
 [0.4        0.4        0.05       0.25092251]
 [0.2        0.1        0.05       0.24723247]]


In [3]:
import numpy as np

a= np.random.randn(5)

In [6]:
print(a)

[-0.86977553  0.12963981 -0.52143128 -0.55235979 -0.60844076]


In [7]:
print(a.shape)

(5,)


In [8]:
print(a.T)

[-0.86977553  0.12963981 -0.52143128 -0.55235979 -0.60844076]


In [10]:
print(a.T.shape)

(5,)


In [11]:
print(np.dot(a, a.T))

1.720508033790523


In [12]:
a.reshape(5,1)

array([[-0.86977553],
       [ 0.12963981],
       [-0.52143128],
       [-0.55235979],
       [-0.60844076]])

In [13]:
b= np.random.randn(5,1)
print(b)
print(b.shape)

[[ 0.46561186]
 [ 0.17309037]
 [ 1.02132353]
 [-0.12807953]
 [-0.89278251]]
(5, 1)


In [14]:
print(np.dot(b, b.T))

[[ 0.21679441  0.08059293  0.47554035 -0.05963535 -0.41569013]
 [ 0.08059293  0.02996028  0.17678127 -0.02216933 -0.15453206]
 [ 0.47554035  0.17678127  1.04310176 -0.13081064 -0.91181979]
 [-0.05963535 -0.02216933 -0.13081064  0.01640437  0.11434717]
 [-0.41569013 -0.15453206 -0.91181979  0.11434717  0.79706061]]


In [21]:
assert(b.shape==(5,1))