<a href="https://colab.research.google.com/github/armandoordonez/deeplearning/blob/main/Matrix_multiplication.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# multiplicación de matrices con bucles

# 3x3 matrix
X = [[12,7,3],
    [4 ,5,6],
    [7 ,8,9]]

# 3x4 matrix
Y = [[5,8,1,2],
    [6,7,3,0],
    [4,5,9,1]]

# result is 3x4
result = [[0,0,0,0],
         [0,0,0,0],
         [0,0,0,0]]


# itera filas de  X
for i in range(len(X)):
   # itera columnas de  Y
   for j in range(len(Y[0])):
       # itera filas de Y
       for k in range(len(Y)):
           result[i][j] += X[i][k] * Y[k][j]

for r in result:
   print(r)

[114, 160, 60, 27]
[74, 97, 73, 14]
[119, 157, 112, 23]


In [4]:
import numpy as np

r = np.dot(X, Y)
print(r)

[[114 160  60  27]
 [ 74  97  73  14]
 [119 157 112  23]]
