<a href="https://colab.research.google.com/github/armandoordonez/deeplearning/blob/main/Broadcasting_example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import numpy as np

A = np.array([[10.0,0.0,4.5,68.0],[30.0,5.0,4.5,68.0],[40.0,4.0,0.5,68.0],[20.0,1.0,0.5,67.0]])
print (A)

[[10.   0.   4.5 68. ]
 [30.   5.   4.5 68. ]
 [40.   4.   0.5 68. ]
 [20.   1.   0.5 67. ]]


In [17]:
suma = np.sum(A, axis=0)
print(suma)

[100.  10.  10. 271.]


In [18]:
print(A/suma)

[[0.1        0.         0.45       0.25092251]
 [0.3        0.5        0.45       0.25092251]
 [0.4        0.4        0.05       0.25092251]
 [0.2        0.1        0.05       0.24723247]]
